default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stat_telega_development

test:
  <<: *default
  database: stat_telega_test

production:
  adapter: postgresql
  encoding: unicode
  database: telega_stat
  pool: 5
  username: <%= Rails.application.credentials.postgres[:username] %>
  password:  <%= Rails.application.credentials.postgres[:password] %> 
  host: <%= Rails.application.credentials.postgres[:host] %>  # remote database server ip
  port: 6432 
  # <<: *default
  # database: stat_telega_production
  # username: stat_telega
  # password: <%= ENV['STAT_TELEGA_DATABASE_PASSWORD'] %>
